[package]
name = "cuda-driver-sys"
version = "0.3.3"
edition = "2021"
authors = ["YangBo <bo.yang@smail.nju.edu.cn>", "tsondru"]
description = "Rust binding to CUDA Driver APIs"
repository = "https://github.com/sustia-llc/cuda-driver-sys"
keywords = ["GPGPU", "CUDA", "ffi"]
license = "Apache-2.0"
readme = "./README.md"
categories = ["external-ffi-bindings"]

build = "build.rs"

links = "cuda-126"

[features]
cuda-static-link = []
cublas = []
